"""Go's named Unicode tables, as offsets into `data.mojo`.

Generated by `tools/gen/unicode.py`. Do not edit: change `tools/gen/ucd.py`
and run `pixi run gen`. `pixi run generated-check` fails on a diff.

Every name Go exports as a `*RangeTable` is here under exactly Go's spelling,
including the underscores in `White_Space` and the capital in `Adlam`, because
a table is a variable and `tools/parity/rules.py` leaves a variable's name
alone. `Digit` really is the same table as `Nd` and is written as an alias of
it, which is what Go does too.

The six functions at the bottom are Go's six maps. They are functions rather
than variables because a `Dict` cannot be a compile time constant, so each one
builds its map when it is called. Calling `Categories()` in a loop allocates a
hundred times; hold the result, or reach for the named table directly, which
is what almost every caller wants anyway.
"""

from .letter import RangeTable

comptime C = RangeTable(0, 289, 320, 2)
"""The `C` general category. Go's `unicode.C`."""

comptime Cc = RangeTable(609, 2, 0, 2)
"""The `Cc` general category. Go's `unicode.Cc`."""

comptime Cf = RangeTable(611, 12, 6, 0)
"""The `Cf` general category. Go's `unicode.Cf`."""

comptime Cn = RangeTable(629, 282, 322, 0)
"""The `Cn` general category. Go's `unicode.Cn`."""

comptime Co = RangeTable(1233, 1, 2, 0)
"""The `Co` general category. Go's `unicode.Co`."""

comptime Cs = RangeTable(1236, 1, 0, 0)
"""The `Cs` general category. Go's `unicode.Cs`."""

comptime L = RangeTable(1237, 359, 264, 6)
"""The `L` general category. Go's `unicode.L`."""

comptime LC = RangeTable(1860, 86, 49, 5)
"""The `LC` general category. Go's `unicode.LC`."""

comptime Ll = RangeTable(1995, 122, 41, 4)
"""The `Ll` general category. Go's `unicode.Ll`."""

comptime Lm = RangeTable(2158, 41, 13, 0)
"""The `Lm` general category. Go's `unicode.Lm`."""

comptime Lo = RangeTable(2212, 279, 205, 1)
"""The `Lo` general category. Go's `unicode.Lo`."""

comptime Lt = RangeTable(2696, 7, 0, 0)
"""The `Lt` general category. Go's `unicode.Lt`."""

comptime Lu = RangeTable(2703, 109, 40, 3)
"""The `Lu` general category. Go's `unicode.Lu`."""

comptime M = RangeTable(2852, 182, 117, 0)
"""The `M` general category. Go's `unicode.M`."""

comptime Mc = RangeTable(3151, 98, 60, 0)
"""The `Mc` general category. Go's `unicode.Mc`."""

comptime Me = RangeTable(3309, 5, 0, 0)
"""The `Me` general category. Go's `unicode.Me`."""

comptime Mn = RangeTable(3314, 183, 125, 0)
"""The `Mn` general category. Go's `unicode.Mn`."""

comptime N = RangeTable(3622, 66, 69, 4)
"""The `N` general category. Go's `unicode.N`."""

comptime Nd = RangeTable(3757, 37, 27, 1)
"""The `Nd` general category. Go's `unicode.Nd`."""

comptime Nl = RangeTable(3821, 7, 4, 0)
"""The `Nl` general category. Go's `unicode.Nl`."""

comptime No = RangeTable(3832, 28, 43, 3)
"""The `No` general category. Go's `unicode.No`."""

comptime P = RangeTable(3903, 115, 52, 11)
"""The `P` general category. Go's `unicode.P`."""

comptime Pc = RangeTable(4070, 5, 0, 0)
"""The `Pc` general category. Go's `unicode.Pc`."""

comptime Pd = RangeTable(4075, 11, 1, 0)
"""The `Pd` general category. Go's `unicode.Pd`."""

comptime Pe = RangeTable(4087, 23, 0, 1)
"""The `Pe` general category. Go's `unicode.Pe`."""

comptime Pf = RangeTable(4110, 5, 0, 0)
"""The `Pf` general category. Go's `unicode.Pf`."""

comptime Pi = RangeTable(4115, 6, 0, 0)
"""The `Pi` general category. Go's `unicode.Pi`."""

comptime Po = RangeTable(4121, 113, 51, 8)
"""The `Po` general category. Go's `unicode.Po`."""

comptime Ps = RangeTable(4285, 26, 0, 1)
"""The `Ps` general category. Go's `unicode.Ps`."""

comptime S = RangeTable(4311, 129, 72, 10)
"""The `S` general category. Go's `unicode.S`."""

comptime Sc = RangeTable(4512, 13, 2, 2)
"""The `Sc` general category. Go's `unicode.Sc`."""

comptime Sk = RangeTable(4527, 25, 1, 3)
"""The `Sk` general category. Go's `unicode.Sk`."""

comptime Sm = RangeTable(4553, 43, 6, 5)
"""The `Sm` general category. Go's `unicode.Sm`."""

comptime So = RangeTable(4602, 99, 67, 2)
"""The `So` general category. Go's `unicode.So`."""

comptime Z = RangeTable(4768, 6, 0, 1)
"""The `Z` general category. Go's `unicode.Z`."""

comptime Zl = RangeTable(4774, 1, 0, 0)
"""The `Zl` general category. Go's `unicode.Zl`."""

comptime Zp = RangeTable(4775, 1, 0, 0)
"""The `Zp` general category. Go's `unicode.Zp`."""

comptime Zs = RangeTable(4776, 5, 0, 1)
"""The `Zs` general category. Go's `unicode.Zs`."""

comptime Adlam = RangeTable(4781, 0, 3, 0)
"""The `Adlam` script. Go's `unicode.Adlam`."""

comptime Ahom = RangeTable(4784, 0, 3, 0)
"""The `Ahom` script. Go's `unicode.Ahom`."""

comptime Anatolian_Hieroglyphs = RangeTable(4787, 0, 1, 0)
"""The `Anatolian_Hieroglyphs` script. Go's `unicode.Anatolian_Hieroglyphs`."""

comptime Arabic = RangeTable(4788, 22, 27, 0)
"""The `Arabic` script. Go's `unicode.Arabic`."""

comptime Armenian = RangeTable(4837, 4, 0, 0)
"""The `Armenian` script. Go's `unicode.Armenian`."""

comptime Avestan = RangeTable(4841, 0, 2, 0)
"""The `Avestan` script. Go's `unicode.Avestan`."""

comptime Balinese = RangeTable(4843, 2, 0, 0)
"""The `Balinese` script. Go's `unicode.Balinese`."""

comptime Bamum = RangeTable(4845, 1, 1, 0)
"""The `Bamum` script. Go's `unicode.Bamum`."""

comptime Bassa_Vah = RangeTable(4847, 0, 2, 0)
"""The `Bassa_Vah` script. Go's `unicode.Bassa_Vah`."""

comptime Batak = RangeTable(4849, 2, 0, 0)
"""The `Batak` script. Go's `unicode.Batak`."""

comptime Bengali = RangeTable(4851, 14, 0, 0)
"""The `Bengali` script. Go's `unicode.Bengali`."""

comptime Bhaiksuki = RangeTable(4865, 0, 4, 0)
"""The `Bhaiksuki` script. Go's `unicode.Bhaiksuki`."""

comptime Bopomofo = RangeTable(4869, 3, 0, 0)
"""The `Bopomofo` script. Go's `unicode.Bopomofo`."""

comptime Brahmi = RangeTable(4872, 0, 3, 0)
"""The `Brahmi` script. Go's `unicode.Brahmi`."""

comptime Braille = RangeTable(4875, 1, 0, 0)
"""The `Braille` script. Go's `unicode.Braille`."""

comptime Buginese = RangeTable(4876, 2, 0, 0)
"""The `Buginese` script. Go's `unicode.Buginese`."""

comptime Buhid = RangeTable(4878, 1, 0, 0)
"""The `Buhid` script. Go's `unicode.Buhid`."""

comptime Canadian_Aboriginal = RangeTable(4879, 2, 1, 0)
"""The `Canadian_Aboriginal` script. Go's `unicode.Canadian_Aboriginal`."""

comptime Carian = RangeTable(4882, 0, 1, 0)
"""The `Carian` script. Go's `unicode.Carian`."""

comptime Caucasian_Albanian = RangeTable(4883, 0, 2, 0)
"""The `Caucasian_Albanian` script. Go's `unicode.Caucasian_Albanian`."""

comptime Chakma = RangeTable(4885, 0, 2, 0)
"""The `Chakma` script. Go's `unicode.Chakma`."""

comptime Cham = RangeTable(4887, 4, 0, 0)
"""The `Cham` script. Go's `unicode.Cham`."""

comptime Cherokee = RangeTable(4891, 3, 0, 0)
"""The `Cherokee` script. Go's `unicode.Cherokee`."""

comptime Chorasmian = RangeTable(4894, 0, 1, 0)
"""The `Chorasmian` script. Go's `unicode.Chorasmian`."""

comptime Common = RangeTable(4895, 82, 82, 6)
"""The `Common` script. Go's `unicode.Common`."""

comptime Coptic = RangeTable(5059, 3, 0, 0)
"""The `Coptic` script. Go's `unicode.Coptic`."""

comptime Cuneiform = RangeTable(5062, 0, 4, 0)
"""The `Cuneiform` script. Go's `unicode.Cuneiform`."""

comptime Cypriot = RangeTable(5066, 0, 5, 0)
"""The `Cypriot` script. Go's `unicode.Cypriot`."""

comptime Cypro_Minoan = RangeTable(5071, 0, 1, 0)
"""The `Cypro_Minoan` script. Go's `unicode.Cypro_Minoan`."""

comptime Cyrillic = RangeTable(5072, 7, 2, 0)
"""The `Cyrillic` script. Go's `unicode.Cyrillic`."""

comptime Deseret = RangeTable(5081, 0, 1, 0)
"""The `Deseret` script. Go's `unicode.Deseret`."""

comptime Devanagari = RangeTable(5082, 4, 1, 0)
"""The `Devanagari` script. Go's `unicode.Devanagari`."""

comptime Dives_Akuru = RangeTable(5087, 0, 8, 0)
"""The `Dives_Akuru` script. Go's `unicode.Dives_Akuru`."""

comptime Dogra = RangeTable(5095, 0, 1, 0)
"""The `Dogra` script. Go's `unicode.Dogra`."""

comptime Duployan = RangeTable(5096, 0, 5, 0)
"""The `Duployan` script. Go's `unicode.Duployan`."""

comptime Egyptian_Hieroglyphs = RangeTable(5101, 0, 1, 0)
"""The `Egyptian_Hieroglyphs` script. Go's `unicode.Egyptian_Hieroglyphs`."""

comptime Elbasan = RangeTable(5102, 0, 1, 0)
"""The `Elbasan` script. Go's `unicode.Elbasan`."""

comptime Elymaic = RangeTable(5103, 0, 1, 0)
"""The `Elymaic` script. Go's `unicode.Elymaic`."""

comptime Ethiopic = RangeTable(5104, 32, 4, 0)
"""The `Ethiopic` script. Go's `unicode.Ethiopic`."""

comptime Georgian = RangeTable(5140, 8, 0, 0)
"""The `Georgian` script. Go's `unicode.Georgian`."""

comptime Glagolitic = RangeTable(5148, 1, 5, 0)
"""The `Glagolitic` script. Go's `unicode.Glagolitic`."""

comptime Gothic = RangeTable(5154, 0, 1, 0)
"""The `Gothic` script. Go's `unicode.Gothic`."""

comptime Grantha = RangeTable(5155, 0, 14, 0)
"""The `Grantha` script. Go's `unicode.Grantha`."""

comptime Greek = RangeTable(5169, 29, 3, 0)
"""The `Greek` script. Go's `unicode.Greek`."""

comptime Gujarati = RangeTable(5201, 14, 0, 0)
"""The `Gujarati` script. Go's `unicode.Gujarati`."""

comptime Gunjala_Gondi = RangeTable(5215, 0, 6, 0)
"""The `Gunjala_Gondi` script. Go's `unicode.Gunjala_Gondi`."""

comptime Gurmukhi = RangeTable(5221, 16, 0, 0)
"""The `Gurmukhi` script. Go's `unicode.Gurmukhi`."""

comptime Han = RangeTable(5237, 10, 10, 0)
"""The `Han` script. Go's `unicode.Han`."""

comptime Hangul = RangeTable(5257, 14, 0, 0)
"""The `Hangul` script. Go's `unicode.Hangul`."""

comptime Hanifi_Rohingya = RangeTable(5271, 0, 2, 0)
"""The `Hanifi_Rohingya` script. Go's `unicode.Hanifi_Rohingya`."""

comptime Hanunoo = RangeTable(5273, 1, 0, 0)
"""The `Hanunoo` script. Go's `unicode.Hanunoo`."""

comptime Hatran = RangeTable(5274, 0, 3, 0)
"""The `Hatran` script. Go's `unicode.Hatran`."""

comptime Hebrew = RangeTable(5277, 9, 0, 0)
"""The `Hebrew` script. Go's `unicode.Hebrew`."""

comptime Hiragana = RangeTable(5286, 2, 4, 0)
"""The `Hiragana` script. Go's `unicode.Hiragana`."""

comptime Imperial_Aramaic = RangeTable(5292, 0, 2, 0)
"""The `Imperial_Aramaic` script. Go's `unicode.Imperial_Aramaic`."""

comptime Inherited = RangeTable(5294, 18, 9, 0)
"""The `Inherited` script. Go's `unicode.Inherited`."""

comptime Inscriptional_Pahlavi = RangeTable(5321, 0, 2, 0)
"""The `Inscriptional_Pahlavi` script. Go's `unicode.Inscriptional_Pahlavi`."""

comptime Inscriptional_Parthian = RangeTable(5323, 0, 2, 0)
"""The `Inscriptional_Parthian` script. Go's `unicode.Inscriptional_Parthian`."""

comptime Javanese = RangeTable(5325, 3, 0, 0)
"""The `Javanese` script. Go's `unicode.Javanese`."""

comptime Kaithi = RangeTable(5328, 0, 2, 0)
"""The `Kaithi` script. Go's `unicode.Kaithi`."""

comptime Kannada = RangeTable(5330, 13, 0, 0)
"""The `Kannada` script. Go's `unicode.Kannada`."""

comptime Katakana = RangeTable(5343, 7, 7, 0)
"""The `Katakana` script. Go's `unicode.Katakana`."""

comptime Kawi = RangeTable(5357, 0, 3, 0)
"""The `Kawi` script. Go's `unicode.Kawi`."""

comptime Kayah_Li = RangeTable(5360, 2, 0, 0)
"""The `Kayah_Li` script. Go's `unicode.Kayah_Li`."""

comptime Kharoshthi = RangeTable(5362, 0, 8, 0)
"""The `Kharoshthi` script. Go's `unicode.Kharoshthi`."""

comptime Khitan_Small_Script = RangeTable(5370, 0, 2, 0)
"""The `Khitan_Small_Script` script. Go's `unicode.Khitan_Small_Script`."""

comptime Khmer = RangeTable(5372, 4, 0, 0)
"""The `Khmer` script. Go's `unicode.Khmer`."""

comptime Khojki = RangeTable(5376, 0, 2, 0)
"""The `Khojki` script. Go's `unicode.Khojki`."""

comptime Khudawadi = RangeTable(5378, 0, 2, 0)
"""The `Khudawadi` script. Go's `unicode.Khudawadi`."""

comptime Lao = RangeTable(5380, 11, 0, 0)
"""The `Lao` script. Go's `unicode.Lao`."""

comptime Latin = RangeTable(5391, 31, 5, 5)
"""The `Latin` script. Go's `unicode.Latin`."""

comptime Lepcha = RangeTable(5427, 3, 0, 0)
"""The `Lepcha` script. Go's `unicode.Lepcha`."""

comptime Limbu = RangeTable(5430, 5, 0, 0)
"""The `Limbu` script. Go's `unicode.Limbu`."""

comptime Linear_A = RangeTable(5435, 0, 3, 0)
"""The `Linear_A` script. Go's `unicode.Linear_A`."""

comptime Linear_B = RangeTable(5438, 0, 7, 0)
"""The `Linear_B` script. Go's `unicode.Linear_B`."""

comptime Lisu = RangeTable(5445, 1, 1, 0)
"""The `Lisu` script. Go's `unicode.Lisu`."""

comptime Lycian = RangeTable(5447, 0, 1, 0)
"""The `Lycian` script. Go's `unicode.Lycian`."""

comptime Lydian = RangeTable(5448, 0, 2, 0)
"""The `Lydian` script. Go's `unicode.Lydian`."""

comptime Mahajani = RangeTable(5450, 0, 1, 0)
"""The `Mahajani` script. Go's `unicode.Mahajani`."""

comptime Makasar = RangeTable(5451, 0, 1, 0)
"""The `Makasar` script. Go's `unicode.Makasar`."""

comptime Malayalam = RangeTable(5452, 7, 0, 0)
"""The `Malayalam` script. Go's `unicode.Malayalam`."""

comptime Mandaic = RangeTable(5459, 2, 0, 0)
"""The `Mandaic` script. Go's `unicode.Mandaic`."""

comptime Manichaean = RangeTable(5461, 0, 2, 0)
"""The `Manichaean` script. Go's `unicode.Manichaean`."""

comptime Marchen = RangeTable(5463, 0, 3, 0)
"""The `Marchen` script. Go's `unicode.Marchen`."""

comptime Masaram_Gondi = RangeTable(5466, 0, 7, 0)
"""The `Masaram_Gondi` script. Go's `unicode.Masaram_Gondi`."""

comptime Medefaidrin = RangeTable(5473, 0, 1, 0)
"""The `Medefaidrin` script. Go's `unicode.Medefaidrin`."""

comptime Meetei_Mayek = RangeTable(5474, 3, 0, 0)
"""The `Meetei_Mayek` script. Go's `unicode.Meetei_Mayek`."""

comptime Mende_Kikakui = RangeTable(5477, 0, 2, 0)
"""The `Mende_Kikakui` script. Go's `unicode.Mende_Kikakui`."""

comptime Meroitic_Cursive = RangeTable(5479, 0, 3, 0)
"""The `Meroitic_Cursive` script. Go's `unicode.Meroitic_Cursive`."""

comptime Meroitic_Hieroglyphs = RangeTable(5482, 0, 1, 0)
"""The `Meroitic_Hieroglyphs` script. Go's `unicode.Meroitic_Hieroglyphs`."""

comptime Miao = RangeTable(5483, 0, 3, 0)
"""The `Miao` script. Go's `unicode.Miao`."""

comptime Modi = RangeTable(5486, 0, 2, 0)
"""The `Modi` script. Go's `unicode.Modi`."""

comptime Mongolian = RangeTable(5488, 5, 1, 0)
"""The `Mongolian` script. Go's `unicode.Mongolian`."""

comptime Mro = RangeTable(5494, 0, 3, 0)
"""The `Mro` script. Go's `unicode.Mro`."""

comptime Multani = RangeTable(5497, 0, 5, 0)
"""The `Multani` script. Go's `unicode.Multani`."""

comptime Myanmar = RangeTable(5502, 3, 0, 0)
"""The `Myanmar` script. Go's `unicode.Myanmar`."""

comptime Nabataean = RangeTable(5505, 0, 2, 0)
"""The `Nabataean` script. Go's `unicode.Nabataean`."""

comptime Nag_Mundari = RangeTable(5507, 0, 1, 0)
"""The `Nag_Mundari` script. Go's `unicode.Nag_Mundari`."""

comptime Nandinagari = RangeTable(5508, 0, 3, 0)
"""The `Nandinagari` script. Go's `unicode.Nandinagari`."""

comptime New_Tai_Lue = RangeTable(5511, 4, 0, 0)
"""The `New_Tai_Lue` script. Go's `unicode.New_Tai_Lue`."""

comptime Newa = RangeTable(5515, 0, 2, 0)
"""The `Newa` script. Go's `unicode.Newa`."""

comptime Nko = RangeTable(5517, 2, 0, 0)
"""The `Nko` script. Go's `unicode.Nko`."""

comptime Nushu = RangeTable(5519, 0, 2, 0)
"""The `Nushu` script. Go's `unicode.Nushu`."""

comptime Nyiakeng_Puachue_Hmong = RangeTable(5521, 0, 4, 0)
"""The `Nyiakeng_Puachue_Hmong` script. Go's `unicode.Nyiakeng_Puachue_Hmong`."""

comptime Ogham = RangeTable(5525, 1, 0, 0)
"""The `Ogham` script. Go's `unicode.Ogham`."""

comptime Ol_Chiki = RangeTable(5526, 1, 0, 0)
"""The `Ol_Chiki` script. Go's `unicode.Ol_Chiki`."""

comptime Old_Hungarian = RangeTable(5527, 0, 3, 0)
"""The `Old_Hungarian` script. Go's `unicode.Old_Hungarian`."""

comptime Old_Italic = RangeTable(5530, 0, 2, 0)
"""The `Old_Italic` script. Go's `unicode.Old_Italic`."""

comptime Old_North_Arabian = RangeTable(5532, 0, 1, 0)
"""The `Old_North_Arabian` script. Go's `unicode.Old_North_Arabian`."""

comptime Old_Permic = RangeTable(5533, 0, 1, 0)
"""The `Old_Permic` script. Go's `unicode.Old_Permic`."""

comptime Old_Persian = RangeTable(5534, 0, 2, 0)
"""The `Old_Persian` script. Go's `unicode.Old_Persian`."""

comptime Old_Sogdian = RangeTable(5536, 0, 1, 0)
"""The `Old_Sogdian` script. Go's `unicode.Old_Sogdian`."""

comptime Old_South_Arabian = RangeTable(5537, 0, 1, 0)
"""The `Old_South_Arabian` script. Go's `unicode.Old_South_Arabian`."""

comptime Old_Turkic = RangeTable(5538, 0, 1, 0)
"""The `Old_Turkic` script. Go's `unicode.Old_Turkic`."""

comptime Old_Uyghur = RangeTable(5539, 0, 1, 0)
"""The `Old_Uyghur` script. Go's `unicode.Old_Uyghur`."""

comptime Oriya = RangeTable(5540, 14, 0, 0)
"""The `Oriya` script. Go's `unicode.Oriya`."""

comptime Osage = RangeTable(5554, 0, 2, 0)
"""The `Osage` script. Go's `unicode.Osage`."""

comptime Osmanya = RangeTable(5556, 0, 2, 0)
"""The `Osmanya` script. Go's `unicode.Osmanya`."""

comptime Pahawh_Hmong = RangeTable(5558, 0, 5, 0)
"""The `Pahawh_Hmong` script. Go's `unicode.Pahawh_Hmong`."""

comptime Palmyrene = RangeTable(5563, 0, 1, 0)
"""The `Palmyrene` script. Go's `unicode.Palmyrene`."""

comptime Pau_Cin_Hau = RangeTable(5564, 0, 1, 0)
"""The `Pau_Cin_Hau` script. Go's `unicode.Pau_Cin_Hau`."""

comptime Phags_Pa = RangeTable(5565, 1, 0, 0)
"""The `Phags_Pa` script. Go's `unicode.Phags_Pa`."""

comptime Phoenician = RangeTable(5566, 0, 2, 0)
"""The `Phoenician` script. Go's `unicode.Phoenician`."""

comptime Psalter_Pahlavi = RangeTable(5568, 0, 3, 0)
"""The `Psalter_Pahlavi` script. Go's `unicode.Psalter_Pahlavi`."""

comptime Rejang = RangeTable(5571, 2, 0, 0)
"""The `Rejang` script. Go's `unicode.Rejang`."""

comptime Runic = RangeTable(5573, 2, 0, 0)
"""The `Runic` script. Go's `unicode.Runic`."""

comptime Samaritan = RangeTable(5575, 2, 0, 0)
"""The `Samaritan` script. Go's `unicode.Samaritan`."""

comptime Saurashtra = RangeTable(5577, 2, 0, 0)
"""The `Saurashtra` script. Go's `unicode.Saurashtra`."""

comptime Sharada = RangeTable(5579, 0, 1, 0)
"""The `Sharada` script. Go's `unicode.Sharada`."""

comptime Shavian = RangeTable(5580, 0, 1, 0)
"""The `Shavian` script. Go's `unicode.Shavian`."""

comptime Siddham = RangeTable(5581, 0, 2, 0)
"""The `Siddham` script. Go's `unicode.Siddham`."""

comptime SignWriting = RangeTable(5583, 0, 3, 0)
"""The `SignWriting` script. Go's `unicode.SignWriting`."""

comptime Sinhala = RangeTable(5586, 12, 1, 0)
"""The `Sinhala` script. Go's `unicode.Sinhala`."""

comptime Sogdian = RangeTable(5599, 0, 1, 0)
"""The `Sogdian` script. Go's `unicode.Sogdian`."""

comptime Sora_Sompeng = RangeTable(5600, 0, 2, 0)
"""The `Sora_Sompeng` script. Go's `unicode.Sora_Sompeng`."""

comptime Soyombo = RangeTable(5602, 0, 1, 0)
"""The `Soyombo` script. Go's `unicode.Soyombo`."""

comptime Sundanese = RangeTable(5603, 2, 0, 0)
"""The `Sundanese` script. Go's `unicode.Sundanese`."""

comptime Syloti_Nagri = RangeTable(5605, 1, 0, 0)
"""The `Syloti_Nagri` script. Go's `unicode.Syloti_Nagri`."""

comptime Syriac = RangeTable(5606, 4, 0, 0)
"""The `Syriac` script. Go's `unicode.Syriac`."""

comptime Tagalog = RangeTable(5610, 2, 0, 0)
"""The `Tagalog` script. Go's `unicode.Tagalog`."""

comptime Tagbanwa = RangeTable(5612, 3, 0, 0)
"""The `Tagbanwa` script. Go's `unicode.Tagbanwa`."""

comptime Tai_Le = RangeTable(5615, 2, 0, 0)
"""The `Tai_Le` script. Go's `unicode.Tai_Le`."""

comptime Tai_Tham = RangeTable(5617, 5, 0, 0)
"""The `Tai_Tham` script. Go's `unicode.Tai_Tham`."""

comptime Tai_Viet = RangeTable(5622, 2, 0, 0)
"""The `Tai_Viet` script. Go's `unicode.Tai_Viet`."""

comptime Takri = RangeTable(5624, 0, 2, 0)
"""The `Takri` script. Go's `unicode.Takri`."""

comptime Tamil = RangeTable(5626, 15, 2, 0)
"""The `Tamil` script. Go's `unicode.Tamil`."""

comptime Tangsa = RangeTable(5643, 0, 2, 0)
"""The `Tangsa` script. Go's `unicode.Tangsa`."""

comptime Tangut = RangeTable(5645, 0, 4, 0)
"""The `Tangut` script. Go's `unicode.Tangut`."""

comptime Telugu = RangeTable(5649, 13, 0, 0)
"""The `Telugu` script. Go's `unicode.Telugu`."""

comptime Thaana = RangeTable(5662, 1, 0, 0)
"""The `Thaana` script. Go's `unicode.Thaana`."""

comptime Thai = RangeTable(5663, 2, 0, 0)
"""The `Thai` script. Go's `unicode.Thai`."""

comptime Tibetan = RangeTable(5665, 7, 0, 0)
"""The `Tibetan` script. Go's `unicode.Tibetan`."""

comptime Tifinagh = RangeTable(5672, 3, 0, 0)
"""The `Tifinagh` script. Go's `unicode.Tifinagh`."""

comptime Tirhuta = RangeTable(5675, 0, 2, 0)
"""The `Tirhuta` script. Go's `unicode.Tirhuta`."""

comptime Toto = RangeTable(5677, 0, 1, 0)
"""The `Toto` script. Go's `unicode.Toto`."""

comptime Ugaritic = RangeTable(5678, 0, 2, 0)
"""The `Ugaritic` script. Go's `unicode.Ugaritic`."""

comptime Vai = RangeTable(5680, 1, 0, 0)
"""The `Vai` script. Go's `unicode.Vai`."""

comptime Vithkuqi = RangeTable(5681, 0, 8, 0)
"""The `Vithkuqi` script. Go's `unicode.Vithkuqi`."""

comptime Wancho = RangeTable(5689, 0, 2, 0)
"""The `Wancho` script. Go's `unicode.Wancho`."""

comptime Warang_Citi = RangeTable(5691, 0, 2, 0)
"""The `Warang_Citi` script. Go's `unicode.Warang_Citi`."""

comptime Yezidi = RangeTable(5693, 0, 3, 0)
"""The `Yezidi` script. Go's `unicode.Yezidi`."""

comptime Yi = RangeTable(5696, 2, 0, 0)
"""The `Yi` script. Go's `unicode.Yi`."""

comptime Zanabazar_Square = RangeTable(5698, 0, 1, 0)
"""The `Zanabazar_Square` script. Go's `unicode.Zanabazar_Square`."""

comptime ASCII_Hex_Digit = RangeTable(5699, 3, 0, 3)
"""The `ASCII_Hex_Digit` property. Go's `unicode.ASCII_Hex_Digit`."""

comptime Bidi_Control = RangeTable(5702, 4, 0, 0)
"""The `Bidi_Control` property. Go's `unicode.Bidi_Control`."""

comptime Dash = RangeTable(5706, 13, 1, 0)
"""The `Dash` property. Go's `unicode.Dash`."""

comptime Deprecated = RangeTable(5720, 5, 1, 0)
"""The `Deprecated` property. Go's `unicode.Deprecated`."""

comptime Diacritic = RangeTable(5726, 110, 53, 3)
"""The `Diacritic` property. Go's `unicode.Diacritic`."""

comptime Extender = RangeTable(5889, 15, 8, 0)
"""The `Extender` property. Go's `unicode.Extender`."""

comptime Hex_Digit = RangeTable(5912, 6, 0, 3)
"""The `Hex_Digit` property. Go's `unicode.Hex_Digit`."""

comptime Hyphen = RangeTable(5918, 6, 0, 1)
"""The `Hyphen` property. Go's `unicode.Hyphen`."""

comptime IDS_Binary_Operator = RangeTable(5924, 2, 0, 0)
"""The `IDS_Binary_Operator` property. Go's `unicode.IDS_Binary_Operator`."""

comptime IDS_Trinary_Operator = RangeTable(5926, 1, 0, 0)
"""The `IDS_Trinary_Operator` property. Go's `unicode.IDS_Trinary_Operator`."""

comptime Ideographic = RangeTable(5927, 7, 13, 0)
"""The `Ideographic` property. Go's `unicode.Ideographic`."""

comptime Join_Control = RangeTable(5947, 1, 0, 0)
"""The `Join_Control` property. Go's `unicode.Join_Control`."""

comptime Logical_Order_Exception = RangeTable(5948, 6, 0, 0)
"""The `Logical_Order_Exception` property. Go's `unicode.Logical_Order_Exception`."""

comptime Noncharacter_Code_Point = RangeTable(5954, 2, 16, 0)
"""The `Noncharacter_Code_Point` property. Go's `unicode.Noncharacter_Code_Point`."""

comptime Other_Alphabetic = RangeTable(5972, 148, 82, 0)
"""The `Other_Alphabetic` property. Go's `unicode.Other_Alphabetic`."""

comptime Other_Default_Ignorable_Code_Point = RangeTable(6202, 5, 4, 0)
"""The `Other_Default_Ignorable_Code_Point` property. Go's `unicode.Other_Default_Ignorable_Code_Point`."""

comptime Other_Grapheme_Extend = RangeTable(6211, 10, 6, 0)
"""The `Other_Grapheme_Extend` property. Go's `unicode.Other_Grapheme_Extend`."""

comptime Other_ID_Continue = RangeTable(6227, 3, 0, 0)
"""The `Other_ID_Continue` property. Go's `unicode.Other_ID_Continue`."""

comptime Other_ID_Start = RangeTable(6230, 3, 0, 0)
"""The `Other_ID_Start` property. Go's `unicode.Other_ID_Start`."""

comptime Other_Lowercase = RangeTable(6233, 20, 5, 1)
"""The `Other_Lowercase` property. Go's `unicode.Other_Lowercase`."""

comptime Other_Math = RangeTable(6258, 63, 55, 0)
"""The `Other_Math` property. Go's `unicode.Other_Math`."""

comptime Other_Uppercase = RangeTable(6376, 2, 3, 0)
"""The `Other_Uppercase` property. Go's `unicode.Other_Uppercase`."""

comptime Pattern_Syntax = RangeTable(6381, 24, 0, 10)
"""The `Pattern_Syntax` property. Go's `unicode.Pattern_Syntax`."""

comptime Pattern_White_Space = RangeTable(6405, 4, 0, 2)
"""The `Pattern_White_Space` property. Go's `unicode.Pattern_White_Space`."""

comptime Prepended_Concatenation_Mark = RangeTable(6409, 4, 1, 0)
"""The `Prepended_Concatenation_Mark` property. Go's `unicode.Prepended_Concatenation_Mark`."""

comptime Quotation_Mark = RangeTable(6414, 10, 0, 2)
"""The `Quotation_Mark` property. Go's `unicode.Quotation_Mark`."""

comptime Radical = RangeTable(6424, 3, 0, 0)
"""The `Radical` property. Go's `unicode.Radical`."""

comptime Regional_Indicator = RangeTable(6427, 0, 1, 0)
"""The `Regional_Indicator` property. Go's `unicode.Regional_Indicator`."""

comptime Sentence_Terminal = RangeTable(6428, 38, 27, 1)
"""The `Sentence_Terminal` property. Go's `unicode.Sentence_Terminal`."""

comptime Soft_Dotted = RangeTable(6493, 10, 15, 1)
"""The `Soft_Dotted` property. Go's `unicode.Soft_Dotted`."""

comptime Terminal_Punctuation = RangeTable(6518, 55, 37, 3)
"""The `Terminal_Punctuation` property. Go's `unicode.Terminal_Punctuation`."""

comptime Unified_Ideograph = RangeTable(6610, 8, 7, 0)
"""The `Unified_Ideograph` property. Go's `unicode.Unified_Ideograph`."""

comptime Variation_Selector = RangeTable(6625, 3, 1, 0)
"""The `Variation_Selector` property. Go's `unicode.Variation_Selector`."""

comptime White_Space = RangeTable(6629, 7, 0, 2)
"""The `White_Space` property. Go's `unicode.White_Space`."""

comptime STerm = RangeTable(6428, 38, 27, 1)
"""The `STerm` property. Go's `unicode.STerm`."""

comptime _fold_L = RangeTable(6636, 1, 0, 0)
"""The code points that fold into `L` from outside it."""

comptime _fold_Ll = RangeTable(6637, 108, 10, 3)
"""The code points that fold into `Ll` from outside it."""

comptime _fold_Lt = RangeTable(6755, 9, 0, 0)
"""The code points that fold into `Lt` from outside it."""

comptime _fold_Lu = RangeTable(6764, 109, 10, 4)
"""The code points that fold into `Lu` from outside it."""

comptime _fold_M = RangeTable(6883, 2, 0, 0)
"""The code points that fold into `M` from outside it."""

comptime _fold_Mn = RangeTable(6883, 2, 0, 0)
"""The code points that fold into `Mn` from outside it."""

comptime _fold_Common = RangeTable(6885, 1, 0, 0)
"""The code points that fold into the `Common` script from outside it."""

comptime _fold_Greek = RangeTable(6886, 1, 0, 0)
"""The code points that fold into the `Greek` script from outside it."""

comptime _fold_Inherited = RangeTable(6883, 2, 0, 0)
"""The code points that fold into the `Inherited` script from outside it."""

comptime Digit = Nd
"""Another name for `Nd`, as Go has one. Go's `unicode.Digit`."""

comptime Letter = L
"""Another name for `L`, as Go has one. Go's `unicode.Letter`."""

comptime Lower = Ll
"""Another name for `Ll`, as Go has one. Go's `unicode.Lower`."""

comptime Mark = M
"""Another name for `M`, as Go has one. Go's `unicode.Mark`."""

comptime Number = N
"""Another name for `N`, as Go has one. Go's `unicode.Number`."""

comptime Other = C
"""Another name for `C`, as Go has one. Go's `unicode.Other`."""

comptime Punct = P
"""Another name for `P`, as Go has one. Go's `unicode.Punct`."""

comptime Space = Z
"""Another name for `Z`, as Go has one. Go's `unicode.Space`."""

comptime Symbol = S
"""Another name for `S`, as Go has one. Go's `unicode.Symbol`."""

comptime Title = Lt
"""Another name for `Lt`, as Go has one. Go's `unicode.Title`."""

comptime Upper = Lu
"""Another name for `Lu`, as Go has one. Go's `unicode.Upper`."""


def Categories() -> Dict[String, RangeTable]:
    """Go's `unicode.Categories`: the general categories, by name.

    A new `Dict` on every call, with 38 entries. The named
    tables above are the same data and cost nothing, so reach for one of
    those unless the name is only known at run time.
    """
    var out = Dict[String, RangeTable]()
    out["C"] = C
    out["Cc"] = Cc
    out["Cf"] = Cf
    out["Cn"] = Cn
    out["Co"] = Co
    out["Cs"] = Cs
    out["L"] = L
    out["LC"] = LC
    out["Ll"] = Ll
    out["Lm"] = Lm
    out["Lo"] = Lo
    out["Lt"] = Lt
    out["Lu"] = Lu
    out["M"] = M
    out["Mc"] = Mc
    out["Me"] = Me
    out["Mn"] = Mn
    out["N"] = N
    out["Nd"] = Nd
    out["Nl"] = Nl
    out["No"] = No
    out["P"] = P
    out["Pc"] = Pc
    out["Pd"] = Pd
    out["Pe"] = Pe
    out["Pf"] = Pf
    out["Pi"] = Pi
    out["Po"] = Po
    out["Ps"] = Ps
    out["S"] = S
    out["Sc"] = Sc
    out["Sk"] = Sk
    out["Sm"] = Sm
    out["So"] = So
    out["Z"] = Z
    out["Zl"] = Zl
    out["Zp"] = Zp
    out["Zs"] = Zs
    return out^


def Scripts() -> Dict[String, RangeTable]:
    """Go's `unicode.Scripts`: the scripts, by name.

    A new `Dict` on every call, with 163 entries. The named
    tables above are the same data and cost nothing, so reach for one of
    those unless the name is only known at run time.
    """
    var out = Dict[String, RangeTable]()
    out["Adlam"] = Adlam
    out["Ahom"] = Ahom
    out["Anatolian_Hieroglyphs"] = Anatolian_Hieroglyphs
    out["Arabic"] = Arabic
    out["Armenian"] = Armenian
    out["Avestan"] = Avestan
    out["Balinese"] = Balinese
    out["Bamum"] = Bamum
    out["Bassa_Vah"] = Bassa_Vah
    out["Batak"] = Batak
    out["Bengali"] = Bengali
    out["Bhaiksuki"] = Bhaiksuki
    out["Bopomofo"] = Bopomofo
    out["Brahmi"] = Brahmi
    out["Braille"] = Braille
    out["Buginese"] = Buginese
    out["Buhid"] = Buhid
    out["Canadian_Aboriginal"] = Canadian_Aboriginal
    out["Carian"] = Carian
    out["Caucasian_Albanian"] = Caucasian_Albanian
    out["Chakma"] = Chakma
    out["Cham"] = Cham
    out["Cherokee"] = Cherokee
    out["Chorasmian"] = Chorasmian
    out["Common"] = Common
    out["Coptic"] = Coptic
    out["Cuneiform"] = Cuneiform
    out["Cypriot"] = Cypriot
    out["Cypro_Minoan"] = Cypro_Minoan
    out["Cyrillic"] = Cyrillic
    out["Deseret"] = Deseret
    out["Devanagari"] = Devanagari
    out["Dives_Akuru"] = Dives_Akuru
    out["Dogra"] = Dogra
    out["Duployan"] = Duployan
    out["Egyptian_Hieroglyphs"] = Egyptian_Hieroglyphs
    out["Elbasan"] = Elbasan
    out["Elymaic"] = Elymaic
    out["Ethiopic"] = Ethiopic
    out["Georgian"] = Georgian
    out["Glagolitic"] = Glagolitic
    out["Gothic"] = Gothic
    out["Grantha"] = Grantha
    out["Greek"] = Greek
    out["Gujarati"] = Gujarati
    out["Gunjala_Gondi"] = Gunjala_Gondi
    out["Gurmukhi"] = Gurmukhi
    out["Han"] = Han
    out["Hangul"] = Hangul
    out["Hanifi_Rohingya"] = Hanifi_Rohingya
    out["Hanunoo"] = Hanunoo
    out["Hatran"] = Hatran
    out["Hebrew"] = Hebrew
    out["Hiragana"] = Hiragana
    out["Imperial_Aramaic"] = Imperial_Aramaic
    out["Inherited"] = Inherited
    out["Inscriptional_Pahlavi"] = Inscriptional_Pahlavi
    out["Inscriptional_Parthian"] = Inscriptional_Parthian
    out["Javanese"] = Javanese
    out["Kaithi"] = Kaithi
    out["Kannada"] = Kannada
    out["Katakana"] = Katakana
    out["Kawi"] = Kawi
    out["Kayah_Li"] = Kayah_Li
    out["Kharoshthi"] = Kharoshthi
    out["Khitan_Small_Script"] = Khitan_Small_Script
    out["Khmer"] = Khmer
    out["Khojki"] = Khojki
    out["Khudawadi"] = Khudawadi
    out["Lao"] = Lao
    out["Latin"] = Latin
    out["Lepcha"] = Lepcha
    out["Limbu"] = Limbu
    out["Linear_A"] = Linear_A
    out["Linear_B"] = Linear_B
    out["Lisu"] = Lisu
    out["Lycian"] = Lycian
    out["Lydian"] = Lydian
    out["Mahajani"] = Mahajani
    out["Makasar"] = Makasar
    out["Malayalam"] = Malayalam
    out["Mandaic"] = Mandaic
    out["Manichaean"] = Manichaean
    out["Marchen"] = Marchen
    out["Masaram_Gondi"] = Masaram_Gondi
    out["Medefaidrin"] = Medefaidrin
    out["Meetei_Mayek"] = Meetei_Mayek
    out["Mende_Kikakui"] = Mende_Kikakui
    out["Meroitic_Cursive"] = Meroitic_Cursive
    out["Meroitic_Hieroglyphs"] = Meroitic_Hieroglyphs
    out["Miao"] = Miao
    out["Modi"] = Modi
    out["Mongolian"] = Mongolian
    out["Mro"] = Mro
    out["Multani"] = Multani
    out["Myanmar"] = Myanmar
    out["Nabataean"] = Nabataean
    out["Nag_Mundari"] = Nag_Mundari
    out["Nandinagari"] = Nandinagari
    out["New_Tai_Lue"] = New_Tai_Lue
    out["Newa"] = Newa
    out["Nko"] = Nko
    out["Nushu"] = Nushu
    out["Nyiakeng_Puachue_Hmong"] = Nyiakeng_Puachue_Hmong
    out["Ogham"] = Ogham
    out["Ol_Chiki"] = Ol_Chiki
    out["Old_Hungarian"] = Old_Hungarian
    out["Old_Italic"] = Old_Italic
    out["Old_North_Arabian"] = Old_North_Arabian
    out["Old_Permic"] = Old_Permic
    out["Old_Persian"] = Old_Persian
    out["Old_Sogdian"] = Old_Sogdian
    out["Old_South_Arabian"] = Old_South_Arabian
    out["Old_Turkic"] = Old_Turkic
    out["Old_Uyghur"] = Old_Uyghur
    out["Oriya"] = Oriya
    out["Osage"] = Osage
    out["Osmanya"] = Osmanya
    out["Pahawh_Hmong"] = Pahawh_Hmong
    out["Palmyrene"] = Palmyrene
    out["Pau_Cin_Hau"] = Pau_Cin_Hau
    out["Phags_Pa"] = Phags_Pa
    out["Phoenician"] = Phoenician
    out["Psalter_Pahlavi"] = Psalter_Pahlavi
    out["Rejang"] = Rejang
    out["Runic"] = Runic
    out["Samaritan"] = Samaritan
    out["Saurashtra"] = Saurashtra
    out["Sharada"] = Sharada
    out["Shavian"] = Shavian
    out["Siddham"] = Siddham
    out["SignWriting"] = SignWriting
    out["Sinhala"] = Sinhala
    out["Sogdian"] = Sogdian
    out["Sora_Sompeng"] = Sora_Sompeng
    out["Soyombo"] = Soyombo
    out["Sundanese"] = Sundanese
    out["Syloti_Nagri"] = Syloti_Nagri
    out["Syriac"] = Syriac
    out["Tagalog"] = Tagalog
    out["Tagbanwa"] = Tagbanwa
    out["Tai_Le"] = Tai_Le
    out["Tai_Tham"] = Tai_Tham
    out["Tai_Viet"] = Tai_Viet
    out["Takri"] = Takri
    out["Tamil"] = Tamil
    out["Tangsa"] = Tangsa
    out["Tangut"] = Tangut
    out["Telugu"] = Telugu
    out["Thaana"] = Thaana
    out["Thai"] = Thai
    out["Tibetan"] = Tibetan
    out["Tifinagh"] = Tifinagh
    out["Tirhuta"] = Tirhuta
    out["Toto"] = Toto
    out["Ugaritic"] = Ugaritic
    out["Vai"] = Vai
    out["Vithkuqi"] = Vithkuqi
    out["Wancho"] = Wancho
    out["Warang_Citi"] = Warang_Citi
    out["Yezidi"] = Yezidi
    out["Yi"] = Yi
    out["Zanabazar_Square"] = Zanabazar_Square
    return out^


def Properties() -> Dict[String, RangeTable]:
    """Go's `unicode.Properties`: the binary properties, by name.

    A new `Dict` on every call, with 35 entries. The named
    tables above are the same data and cost nothing, so reach for one of
    those unless the name is only known at run time.
    """
    var out = Dict[String, RangeTable]()
    out["ASCII_Hex_Digit"] = ASCII_Hex_Digit
    out["Bidi_Control"] = Bidi_Control
    out["Dash"] = Dash
    out["Deprecated"] = Deprecated
    out["Diacritic"] = Diacritic
    out["Extender"] = Extender
    out["Hex_Digit"] = Hex_Digit
    out["Hyphen"] = Hyphen
    out["IDS_Binary_Operator"] = IDS_Binary_Operator
    out["IDS_Trinary_Operator"] = IDS_Trinary_Operator
    out["Ideographic"] = Ideographic
    out["Join_Control"] = Join_Control
    out["Logical_Order_Exception"] = Logical_Order_Exception
    out["Noncharacter_Code_Point"] = Noncharacter_Code_Point
    out["Other_Alphabetic"] = Other_Alphabetic
    out[
        "Other_Default_Ignorable_Code_Point"
    ] = Other_Default_Ignorable_Code_Point
    out["Other_Grapheme_Extend"] = Other_Grapheme_Extend
    out["Other_ID_Continue"] = Other_ID_Continue
    out["Other_ID_Start"] = Other_ID_Start
    out["Other_Lowercase"] = Other_Lowercase
    out["Other_Math"] = Other_Math
    out["Other_Uppercase"] = Other_Uppercase
    out["Pattern_Syntax"] = Pattern_Syntax
    out["Pattern_White_Space"] = Pattern_White_Space
    out["Prepended_Concatenation_Mark"] = Prepended_Concatenation_Mark
    out["Quotation_Mark"] = Quotation_Mark
    out["Radical"] = Radical
    out["Regional_Indicator"] = Regional_Indicator
    out["Sentence_Terminal"] = Sentence_Terminal
    out["Soft_Dotted"] = Soft_Dotted
    out["Terminal_Punctuation"] = Terminal_Punctuation
    out["Unified_Ideograph"] = Unified_Ideograph
    out["Variation_Selector"] = Variation_Selector
    out["White_Space"] = White_Space
    out["STerm"] = STerm
    return out^


def FoldCategory() -> Dict[String, RangeTable]:
    """Go's `unicode.FoldCategory`: the fold exceptions of each category, by name.

    A new `Dict` on every call, with 6 entries. The named
    tables above are the same data and cost nothing, so reach for one of
    those unless the name is only known at run time.
    """
    var out = Dict[String, RangeTable]()
    out["L"] = _fold_L
    out["Ll"] = _fold_Ll
    out["Lt"] = _fold_Lt
    out["Lu"] = _fold_Lu
    out["M"] = _fold_M
    out["Mn"] = _fold_Mn
    return out^


def FoldScript() -> Dict[String, RangeTable]:
    """Go's `unicode.FoldScript`: the fold exceptions of each script, by name.

    A new `Dict` on every call, with 3 entries. The named
    tables above are the same data and cost nothing, so reach for one of
    those unless the name is only known at run time.
    """
    var out = Dict[String, RangeTable]()
    out["Common"] = _fold_Common
    out["Greek"] = _fold_Greek
    out["Inherited"] = _fold_Inherited
    return out^


def CategoryAliases() -> Dict[String, String]:
    """Go's `unicode.CategoryAliases`: `Uppercase_Letter` is `Lu`.

    The long names Unicode gives the general categories, mapped to the
    two letter ones the tables above are keyed by. Nothing in this
    package reads it; it is here because a program taking a category
    name from a user has to accept both spellings.
    """
    var out = Dict[String, String]()
    out["Cased_Letter"] = "LC"
    out["Close_Punctuation"] = "Pe"
    out["Combining_Mark"] = "M"
    out["Connector_Punctuation"] = "Pc"
    out["Control"] = "Cc"
    out["Currency_Symbol"] = "Sc"
    out["Dash_Punctuation"] = "Pd"
    out["Decimal_Number"] = "Nd"
    out["Enclosing_Mark"] = "Me"
    out["Final_Punctuation"] = "Pf"
    out["Format"] = "Cf"
    out["Initial_Punctuation"] = "Pi"
    out["Letter"] = "L"
    out["Letter_Number"] = "Nl"
    out["Line_Separator"] = "Zl"
    out["Lowercase_Letter"] = "Ll"
    out["Mark"] = "M"
    out["Math_Symbol"] = "Sm"
    out["Modifier_Letter"] = "Lm"
    out["Modifier_Symbol"] = "Sk"
    out["Nonspacing_Mark"] = "Mn"
    out["Number"] = "N"
    out["Open_Punctuation"] = "Ps"
    out["Other"] = "C"
    out["Other_Letter"] = "Lo"
    out["Other_Number"] = "No"
    out["Other_Punctuation"] = "Po"
    out["Other_Symbol"] = "So"
    out["Paragraph_Separator"] = "Zp"
    out["Private_Use"] = "Co"
    out["Punctuation"] = "P"
    out["Separator"] = "Z"
    out["Space_Separator"] = "Zs"
    out["Spacing_Mark"] = "Mc"
    out["Surrogate"] = "Cs"
    out["Symbol"] = "S"
    out["Titlecase_Letter"] = "Lt"
    out["Unassigned"] = "Cn"
    out["Uppercase_Letter"] = "Lu"
    out["cntrl"] = "Cc"
    out["digit"] = "Nd"
    out["punct"] = "P"
    return out^
