#!/usr/bin/env python3
"""Convert Go's table driven tests into Mojo test data.

11,598 symbols cannot be tested by writing tests for them one at a time. Go's
standard library ships roughly 400,000 lines of test code under a BSD licence,
it encodes two decades of bugs found in production, and it is the highest value
asset available to this project. So we take those tests rather than write our
own, and spend the effort saved on the things they cannot check.

The conversion works in three tiers, described in docs/testing.md. This tool
does the first one, the mechanical one: a slice of input and expected output
pairs plus a loop, where the table is data and the loop is boilerplate. The
reading is done by a small Go program, because go/ast is exactly the right tool
for reading Go and is the reason that package is excluded from this library
rather than ported. Evaluating is done by Go itself, since a table is written
as expressions rather than as literals and an evaluator for a subset of Go is
the kind of thing that is subtly wrong for years. See extract.go.

The Go it runs against is the one pixi.lock pins, not whichever one is on PATH.
Two releases of Go do not have to agree about the last bit of a Bessel function
and a harvest that silently changed with the machine would be worthless as a
diff.

This runs offline and its output is checked in. A build that needs a Go
toolchain present is a build that breaks, and re-running this against a new Go
release is a deliberate act producing a reviewable diff. That diff is also how
we notice Go fixing a bug we have.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.tree import ROOT, report

# Which Go packages to harvest and where their output goes. Reviewed as a file
# rather than passed as a flag, so that adding a package to the harvest is a
# change somebody looked at.
PLAN = Path(__file__).parent / "plan.toml"
EXTRACT = Path(__file__).parent / "extract.go"
FMTCASES = Path(__file__).parent / "fmtcases" / "main.go"
OUT = ROOT / "tests" / "generated"
LOCK = ROOT / "pixi.lock"
# `.../go-1.26.7-h1234567_0.conda`, the same line tools/gen/goapi.py reads.
PIN = re.compile(r"/go-(\d[^-]*)-[^/]*\.conda$")

# Every harvested file carries this. Not a formality: a core library that
# vendors somebody else's tests without attribution is a legal problem for
# everyone who ships it.
HEADER = """# Generated by tools/testgen from {source}.
#
# Copyright (c) 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD style licence, which is
# reproduced in full in third_party/go/LICENSE.
#
# Do not edit. Change the generator or the plan, and regenerate.
"""


def pinned() -> str | None:
    """The Go release pixi.lock installs, spelled the way GOTOOLCHAIN wants it.

    One entry per platform and all of them are the same release. A lock file
    that pinned two is worth stopping on rather than picking from, which is why
    this collects them before it chooses.
    """
    if not LOCK.is_file():
        return None
    found = {f"go{m.group(1)}" for m in (PIN.search(line.strip()) for line in LOCK.read_text().splitlines()) if m}
    return found.pop() if len(found) == 1 else None


def environment() -> dict[str, str] | None:
    """The environment the Go commands run under, or None when Go is missing.

    `GOTOOLCHAIN` is what makes the version pinned rather than merely hoped
    for. Go will fetch the release named there if the one on PATH is not it,
    which is the behaviour we want on a machine that has some other Go.
    """
    if not shutil.which("go"):
        return None
    release = pinned()
    if release is None:
        return None
    return {**os.environ, "GOFLAGS": "-mod=mod", "GOTOOLCHAIN": release}


def goroot(env: dict[str, str]) -> Path | None:
    """Where the pinned Go's source is, or None when it is not usable."""
    out = subprocess.run(["go", "env", "GOROOT"], capture_output=True, text=True, env=env)
    if out.returncode != 0:
        return None
    root = Path(out.stdout.strip())
    return root if (root / "src").is_dir() else None


def plan() -> dict[str, dict]:
    if not PLAN.is_file():
        return {}
    with PLAN.open("rb") as fh:
        return tomllib.load(fh).get("harvest", {})


def command_for(name: str, entry: dict, src: Path) -> list[str] | str:
    """What to run for one entry of the plan, or why it cannot be run.

    Almost every entry is a set of tables and goes through the extractor. `fmt`
    is the exception and says so with `mode = "calls"`: its format strings are
    compile time parameters, so there is no loop for a table to be walked by
    and each row has to become its own call. That is code rather than data and
    it has a generator of its own.
    """
    package = src / "src" / entry["go"]
    if not package.is_dir():
        return f"{name}: {entry['go']} is not in this Go tree"

    if entry.get("mode") == "calls":
        source = package / entry["file"]
        if not source.is_file():
            return f"{name}: {entry['file']} is not in this Go tree"
        return ["go", "run", str(FMTCASES), "-file", str(source)]

    # `skip` is optional and almost always absent. It is there for a package
    # whose test files declare something that cannot be copied out of them,
    # which in practice means a declaration calling into export_test.go.
    command = ["go", "run", str(EXTRACT), "-package", str(package), "-tables", ",".join(entry["tables"])]
    if entry.get("skip"):
        command += ["-skip", ",".join(entry["skip"])]
    return command


def harvest(name: str, entry: dict, src: Path, env: dict[str, str]) -> str | None:
    """Run the right generator over one Go package and write the Mojo."""
    command = command_for(name, entry, src)
    if isinstance(command, str):
        return command

    out = subprocess.run(command, capture_output=True, text=True, env=env)
    if out.returncode != 0:
        detail = out.stderr.strip().splitlines()
        return f"{name}: the extractor failed, {detail[-1] if detail else 'no output'}"

    # A harvest that emits calls emits tests, so it is named the way the runner
    # collects them. A harvest that emits data is read by a test written by
    # hand beside it and is named after the package.
    stem = f"test_{name}" if entry.get("mode") == "calls" else name
    target = OUT / f"{stem}.mojo"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(HEADER.format(source=entry["go"]) + "\n" + out.stdout)

    # Formatted here rather than left to whoever runs `pixi run format` next.
    # Generated code that fails the format check is generated code that has to
    # be touched by hand before it can be committed, which is the one thing it
    # is not supposed to need.
    shaped = subprocess.run(["mojo", "format", str(target)], capture_output=True, text=True)
    if shaped.returncode != 0:
        return f"{name}: the formatter refused the generated file, {shaped.stderr.strip()}"

    print(f"testgen: wrote {target.relative_to(ROOT)}")
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("package", nargs="?", help="harvest one entry from the plan")
    args = parser.parse_args()

    entries = plan()
    if args.package:
        entries = {k: v for k, v in entries.items() if k == args.package}
        if not entries:
            print(f"testgen: nothing named {args.package} in the plan", file=sys.stderr)
            return 1
    if not entries:
        print("testgen: the plan is empty, nothing to harvest")
        return 0

    env = environment()
    if env is None:
        print("testgen: no Go toolchain here, use `pixi run -e oracle testgen`", file=sys.stderr)
        return 1
    src = goroot(env)
    if src is None:
        print(f"testgen: {env['GOTOOLCHAIN']} has no source tree here", file=sys.stderr)
        return 1
    for tool in (EXTRACT, FMTCASES):
        if not tool.is_file():
            print(f"testgen: {tool.name} is missing, so nothing can be parsed", file=sys.stderr)
            return 1
    print(f"testgen: against the {env['GOTOOLCHAIN']} tree at {src}")

    problems = [p for p in (harvest(k, v, src, env) for k, v in sorted(entries.items())) if p]
    return report("testgen", len(entries), "packages", problems)


if __name__ == "__main__":
    raise SystemExit(main())
