#!/usr/bin/env python3
"""Convert Go's table driven tests into Mojo test data.

11,598 symbols cannot be tested by writing tests for them one at a time. Go's
standard library ships roughly 400,000 lines of test code under a BSD licence,
it encodes two decades of bugs found in production, and it is the highest value
asset available to this project. So we take those tests rather than write our
own, and spend the effort saved on the things they cannot check.

The conversion works in three tiers, described in docs/testing.md. This tool
does the first one, the mechanical one: a slice of input and expected output
pairs plus a loop, where the table is data and the loop is boilerplate. The
parsing is done by a small Go program, because go/ast is exactly the right tool
for reading Go and is the reason that package is excluded from this library
rather than ported.

This runs offline and its output is checked in. A build that needs a Go
toolchain present is a build that breaks, and re-running this against a new Go
release is a deliberate act producing a reviewable diff. That diff is also how
we notice Go fixing a bug we have.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.tree import ROOT, report

# Which Go packages to harvest and where their output goes. Reviewed as a file
# rather than passed as a flag, so that adding a package to the harvest is a
# change somebody looked at.
PLAN = Path(__file__).parent / "plan.toml"
EXTRACT = Path(__file__).parent / "extract.go"
OUT = ROOT / "tests" / "generated"

# Every harvested file carries this. Not a formality: a core library that
# vendors somebody else's tests without attribution is a legal problem for
# everyone who ships it.
HEADER = """# Generated by tools/testgen from {source}.
#
# Copyright (c) 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD style licence, which is
# reproduced in full in third_party/go/LICENSE.
#
# Do not edit. Change the generator or the plan, and regenerate.
"""


def goroot() -> Path | None:
    """Where Go's source is, or None when there is no Go here."""
    if not shutil.which("go"):
        return None
    out = subprocess.run(["go", "env", "GOROOT"], capture_output=True, text=True)
    if out.returncode != 0:
        return None
    root = Path(out.stdout.strip())
    return root if (root / "src").is_dir() else None


def plan() -> dict[str, dict]:
    if not PLAN.is_file():
        return {}
    with PLAN.open("rb") as fh:
        return tomllib.load(fh).get("harvest", {})


def harvest(name: str, entry: dict, src: Path) -> str | None:
    """Run the extractor over one Go package and write the Mojo table."""
    package = src / "src" / entry["go"]
    if not package.is_dir():
        return f"{name}: {entry['go']} is not in this Go tree"

    out = subprocess.run(
        ["go", "run", str(EXTRACT), "-package", str(package), "-tables", ",".join(entry["tables"])],
        capture_output=True,
        text=True,
        env={**os.environ, "GOFLAGS": "-mod=mod"},
    )
    if out.returncode != 0:
        detail = out.stderr.strip().splitlines()
        return f"{name}: the extractor failed, {detail[-1] if detail else 'no output'}"

    target = OUT / f"{name}.mojo"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(HEADER.format(source=entry["go"]) + "\n" + out.stdout)
    print(f"testgen: wrote {target.relative_to(ROOT)}")
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("package", nargs="?", help="harvest one entry from the plan")
    args = parser.parse_args()

    entries = plan()
    if args.package:
        entries = {k: v for k, v in entries.items() if k == args.package}
        if not entries:
            print(f"testgen: nothing named {args.package} in the plan", file=sys.stderr)
            return 1
    if not entries:
        print("testgen: the plan is empty, nothing to harvest")
        return 0

    src = goroot()
    if src is None:
        print("testgen: no Go toolchain here, use `pixi run -e oracle testgen`", file=sys.stderr)
        return 1
    if not EXTRACT.is_file():
        print(f"testgen: {EXTRACT.name} is missing, so nothing can be parsed", file=sys.stderr)
        return 1
    print(f"testgen: against the Go tree at {src}")

    problems = [p for p in (harvest(k, v, src) for k, v in sorted(entries.items())) if p]
    return report("testgen", len(entries), "packages", problems)


if __name__ == "__main__":
    raise SystemExit(main())
