#!/usr/bin/env python3
"""Run the test suite.

The whole suite is one binary. The runner generates a main that calls every
test function it found, builds it once and runs it, so the build time tracks
the size of the library rather than the number of tests. A library heading for
tens of thousands of test cases cannot afford a process per case.

Takes an optional package name to run one package: `pixi run test core.json`.
Pass --short to skip the tests that take minutes, which is what a local run
wants and what CI does not do.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.tree import ROOT, report

TESTS = ROOT / "tests"

# Go's convention, kept, because a reader coming from Go already knows it and
# because the harvested tests arrive with these names.
TEST_FN = re.compile(r"^\s*def\s+(test_[a-z_0-9]+)\s*\(\s*\)", re.M)


def cases(package: str | None) -> list[tuple[Path, str]]:
    """Every test function in the tree, as a file and a name."""
    if not TESTS.is_dir():
        return []
    found = []
    for path in sorted(TESTS.rglob("test_*.mojo")):
        if package and package.replace("core.", "").replace(".", "/") not in str(path):
            continue
        for name in TEST_FN.findall(path.read_text()):
            found.append((path, name))
    return found


def write_main(found: list[tuple[Path, str]], target: Path, short: bool) -> None:
    """Generate the one main that calls all of them."""
    lines = ["# Generated by tools/mojotest/run.py. Do not edit.", ""]
    modules = sorted({path.relative_to(ROOT).with_suffix("") for path, _ in found})
    for module in modules:
        lines.append(f"import {str(module).replace('/', '.')}")
    lines.append("")
    lines.append("def main():")
    lines.append(f"    var short = {'True' if short else 'False'}")
    lines.append("    var failed = 0")
    for path, name in found:
        module = str(path.relative_to(ROOT).with_suffix("")).replace("/", ".")
        lines.append("    try:")
        lines.append(f"        {module}.{name}()")
        lines.append("    except e:")
        lines.append("        failed += 1")
        lines.append(f'        print("FAIL {module}.{name}:", e)')
    lines.append(f"    print(\"ran {len(found)} tests,\", failed, \"failed\")")
    lines.append("    if failed:")
    lines.append("        raise Error('test suite failed')")
    lines.append("")
    target.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("package", nargs="?", help="run one package")
    parser.add_argument("--short", action="store_true", help="skip the slow cases")
    args = parser.parse_args()

    found = cases(args.package)
    if not found:
        where = args.package or "the tree"
        print(f"test: no tests in {where} yet")
        return 0
    if not shutil.which("mojo"):
        print("test: mojo is not on PATH", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as scratch:
        entry = Path(scratch) / "suite.mojo"
        binary = Path(scratch) / "suite"
        write_main(found, entry, args.short)
        built = subprocess.run(
            ["mojo", "build", "-I", str(ROOT), "-o", str(binary), str(entry)],
            capture_output=True,
            text=True,
        )
        if built.returncode != 0:
            print(built.stdout + built.stderr, file=sys.stderr)
            return report("test", len(found), "tests", ["the suite did not build"])
        ran = subprocess.run([str(binary)], cwd=ROOT)

    if ran.returncode != 0:
        return report("test", len(found), "tests", ["the suite reported failures"])
    return report("test", len(found), "tests", [])


if __name__ == "__main__":
    raise SystemExit(main())
