"""Counting bits. Go's `LeadingZeros`, `TrailingZeros`, `OnesCount` and `Len`.

Twenty functions, four questions, five widths each. Every one of them is a
single machine instruction on every processor this library builds for, and
`std.bit` is where Mojo spells that instruction, so each function here is a
call and a cast rather than a port of Go's table lookups.

Go carries `len8tab`, `ntz8tab`, `pop8tab` and a pair of de Bruijn tables for
these, generated by `make_tables.go`, because Go's compiler intrinsifies the
functions on some architectures and not on others and the tables are what the
rest run on. Nothing here needs that fallback: `count_leading_zeros` and its
neighbours compile to `clz`, `ctz` and `cnt` through LLVM, and a table that is
never read is a table that is never checked. The answers are the same either
way, which the tests take from Go's own test file to show.
"""

from std.bit import (
    bit_width,
    count_leading_zeros,
    count_trailing_zeros,
    pop_count,
)


comptime UINT_SIZE = 64
"""The width of a `UInt` in bits. Go's `UintSize`.

Go computes it from `^uint(0) >> 63` because it supports 32 bit platforms.
Every platform this library builds for is 64 bit and `docs/platforms.md` is the
list, so this is written down rather than derived, the same way `core.strconv`
writes `INT_SIZE`.
"""


def leading_zeros(x: UInt) -> Int:
    """How many zero bits sit above the highest set bit of `x`.

    ```mojo
    from core.math.bits import leading_zeros

    print(leading_zeros(UInt(1)))  # 63
    ```

    `UINT_SIZE` for zero, which is the answer Go documents and the one the
    hardware gives.

    Go writes this as `UintSize - Len(x)` because its `Len` is the one with the
    table behind it. Here the instruction exists in its own right, so it is
    called rather than derived, and the two agree on every input including
    zero.
    """
    return Int(count_leading_zeros(x))


def leading_zeros8(x: UInt8) -> Int:
    """How many zero bits sit above the highest set bit of `x`. 8 for zero."""
    return Int(count_leading_zeros(x))


def leading_zeros16(x: UInt16) -> Int:
    """How many zero bits sit above the highest set bit of `x`. 16 for zero."""
    return Int(count_leading_zeros(x))


def leading_zeros32(x: UInt32) -> Int:
    """How many zero bits sit above the highest set bit of `x`. 32 for zero."""
    return Int(count_leading_zeros(x))


def leading_zeros64(x: UInt64) -> Int:
    """How many zero bits sit above the highest set bit of `x`. 64 for zero."""
    return Int(count_leading_zeros(x))


def trailing_zeros(x: UInt) -> Int:
    """How many zero bits sit below the lowest set bit of `x`.

    ```mojo
    from core.math.bits import trailing_zeros

    print(trailing_zeros(UInt(8)))  # 3
    ```

    `UINT_SIZE` for zero, which is what Go documents.
    """
    return Int(count_trailing_zeros(x))


def trailing_zeros8(x: UInt8) -> Int:
    """How many zero bits sit below the lowest set bit of `x`. 8 for zero."""
    return Int(count_trailing_zeros(x))


def trailing_zeros16(x: UInt16) -> Int:
    """How many zero bits sit below the lowest set bit of `x`. 16 for zero."""
    return Int(count_trailing_zeros(x))


def trailing_zeros32(x: UInt32) -> Int:
    """How many zero bits sit below the lowest set bit of `x`. 32 for zero."""
    return Int(count_trailing_zeros(x))


def trailing_zeros64(x: UInt64) -> Int:
    """How many zero bits sit below the lowest set bit of `x`. 64 for zero."""
    return Int(count_trailing_zeros(x))


def ones_count(x: UInt) -> Int:
    """How many bits of `x` are set. The population count.

    ```mojo
    from core.math.bits import ones_count

    print(ones_count(UInt(7)))  # 3
    ```
    """
    return Int(pop_count(x))


def ones_count8(x: UInt8) -> Int:
    """How many bits of `x` are set."""
    return Int(pop_count(x))


def ones_count16(x: UInt16) -> Int:
    """How many bits of `x` are set."""
    return Int(pop_count(x))


def ones_count32(x: UInt32) -> Int:
    """How many bits of `x` are set."""
    return Int(pop_count(x))


def ones_count64(x: UInt64) -> Int:
    """How many bits of `x` are set."""
    return Int(pop_count(x))


def len(x: UInt) -> Int:
    """How many bits are needed to write `x`. Zero for zero.

    ```mojo
    from core.math.bits import len as bit_len

    print(bit_len(UInt(255)))  # 8
    ```

    Go calls this `Len` and so does this, which puts a function named `len`
    beside the builtin of the same name. Importing it plainly shadows the
    builtin for the rest of the file, so the example renames it on the way in.
    The alternative was a name Go does not have, and a reader porting Go code
    looking for `bits.Len` would not find it.
    """
    return Int(bit_width(x))


def len8(x: UInt8) -> Int:
    """How many bits are needed to write `x`. Zero for zero."""
    return Int(bit_width(x))


def len16(x: UInt16) -> Int:
    """How many bits are needed to write `x`. Zero for zero."""
    return Int(bit_width(x))


def len32(x: UInt32) -> Int:
    """How many bits are needed to write `x`. Zero for zero."""
    return Int(bit_width(x))


def len64(x: UInt64) -> Int:
    """How many bits are needed to write `x`. Zero for zero."""
    return Int(bit_width(x))
